-- 6T
INSERT INTO AiFavoredItems	(ListType, Favored,	Item, Value) SELECT 'SAILOR_VALKRANA_Techs', 1, 'TECH_6T_PHYSICS', 0
WHERE EXISTS (SELECT TechnologyType FROM Technologies WHERE TechnologyType = 'TECH_6T_PHYSICS');

-- Civilizations Expanded
--('TRAIT_LEADER_SAILOR_VALKRANA_UA', 'SAILOR_VALKRANA_UA_RELIC_SCI');
--('SAILOR_VALKRANA_UA_RELIC_SCI', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD', NULL),
--('SAILOR_VALKRANA_UA_RELIC_SCI', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIC'),
--('SAILOR_VALKRANA_UA_RELIC_SCI', 'YieldType', 'YIELD_SCIENCE'),
--('SAILOR_VALKRANA_UA_RELIC_SCI', 'YieldChange', 1),